---
title: "Informe de Actividad Física"
output: 
pdf_document:
  toc: true
  toc_depth: 2
  toc_float: true
date: "2023-11-30"
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(kableExtra)
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=F}
setwd("C:/Users/Usuario/OneDrive - Universidad de Alcala/Proyectos/FIS - Parques y AF/Informes_pacientes/Pruebas")
load("dta_pacientes.RData")

dta_pacientes <-dta_pacientes %>% 
  mutate(total_pas = light+moderate+vigorous+veryvigorous) %>% 
  mutate(dia = recode(day,  monday = "Lunes",
                      tuesday = "Martes",
                      wednesday = "Miércoles",
                      thursday = "Jueves",
                      friday = "Viernes",
                      saturday = "Sábado",
                      sunday = "Domingo")) %>% 
  group_by(subject)
```

## Resumen actividad física semanal

You can also embed plots, for example:

```{r, echo=FALSE}
tab_1 <-  dta_pacientes %>%
  filter(subject=="d_34") %>%
  select(dia, sedentary, light, moderate, vigorous, veryvigorous, MVPA, total_pas, total_activity_day) %>%
  summarise(
    Total_sedentaria = sum(sedentary),
    Total_ligera = sum(light),
    Total_moderada = sum(moderate),
    Total_vigorosa = sum(vigorous),
    Total_muyvigorosa = sum(veryvigorous),
    Total_MVPA = sum(MVPA),
    Total_PA = sum(total_pas),
    Total_Ac = sum(total_activity_day)) %>% 
  rename('Sedentaria'= Total_sedentaria, 'Ligera'= Total_ligera,'Moderada'= Total_moderada, 
       'Vigorosa'= Total_vigorosa, 'Muy vigorosa'= Total_muyvigorosa, "Actividad moderada a vigorosa" = Total_MVPA, 
       "Actividad física total" = Total_PA, "Actividad total registrada"= Total_Ac) %>% 
  kbl(format = ,align = "c") %>% 
  kable_styling() %>% 
  remove_column(columns = 1)
tab_1
```

## Actividad física diaria
```{r, echo=F}
tab_2 <-  dta_pacientes %>%
  filter(subject=="d_34") %>%
  select(dia, sedentary, light, moderate, vigorous, veryvigorous, MVPA, total_pas, total_activity_day) %>%
  rename('Día de la semana' = dia, 'Sedentaria'= sedentary, 'Ligera'= light,'Moderada'= moderate, 
         'Vigorosa'= vigorous, 'Muy vigorosa'= veryvigorous, "Actividad moderada a vigorosa" = MVPA, 
         "Actividad física total" = total_pas, "Actividad total registrada"= total_activity_day) %>% 
  kbl(format = ,align = "c") %>% 
  kable_styling() %>% 
  remove_column(columns = 1) 
tab_2

```

## Gráfico de tipo de actividad física diaria
```{r, echo=F}
library(ggplot2)
library(reshape2)


dta_long <- dta_pacientes %>% 
  filter(subject=="d_34") %>%
  select(dia, sedentary, light, moderate, vigorous, veryvigorous) %>% 
  melt(dta_pacientes, id.vars=c("subject", "dia"),
         measure.vars=c("light", "moderate", "vigorous", "veryvigorous"),
         variable.name="type_pa",
         value.name="minutes")

ggplot(dta_long, aes(x = dia, y = minutes, fill = type_pa)) +
  geom_col(position = position_dodge()) 

```

